port: 8080
autoStopAfter: 10
servePath: /Users/andreacioni/git/ffmpeg-proxy/test
ffmpeg:
  debugOutput: false
  waitForIndex: 2
  indexFile: "/Users/andreacioni/git/ffmpeg-proxy/test/file.m3u8"
  command: touch
  args:
     - /Users/andreacioni/git/ffmpeg-proxy/test/file.m3u8
  #command: ffmpeg
  #args: 
  # - -fflags nobuffer
  # - -rtsp_transport tcp
  # - -i rtsp://wowzaec2demo.streamlock.net/vod/
  # - -vsync 0
  # -  -copyts
  # - -vcodec copy
  # - -movflags frag_keyframe+empty_moov
  # - -an
  # - -hls_flags delete_segments+append_list
  # - -f segment
  # - -segment_list_flags live
  # - -segment_time 1
  # - -segment_list_size 10
  # - -segment_format mpegts
  # - -segment_list ${outputDir}/index.m3u8
  # - -segment_list_type m3u8
  # - -segment_wrap 100
  # - ${outputDir}/%3d.ts
  outputDir: "/Users/andreacioni/git/ffmpeg-proxy/test"